services:
  mariadb:
    volumes:
      - /home/podshivalova/docker-databases/pamp-clone:/var/lib/mysql
  php:
    image: wodby/drupal:$DRUPAL_TAG
    environment:
      PHP_FPM_CLEAR_ENV: "no"
    volumes:
    - codebase:/var/www/html

  crond:
    image: wodby/drupal:$DRUPAL_TAG
    environment:
      PHP_FPM_CLEAR_ENV: "no"
    volumes:
    - codebase:/var/www/html

  nginx:
    volumes:
    - codebase:/var/www/html

  traefik:
    ports:
      - "80:80"

#  webgrind:
#    volumes:
#    - codebase:/mnt/codebase

volumes:
  codebase:
